### Choix de Dataset
On a choisi le dataset sur le chômage au Maroc pour plusieurs raisons importantes. Tout d'abord, dans notre région Beni Mellal-Khénifra le chômage très répandu, c'est un indicateur crucial qui affecte directement la qualité de vie des citoyens et la stabilité économique du pays. En étudiant ces données, on peut identifier les tendances et les disparités régionales, de plus,le Maroc fait face à des défis spécifiques,notamment le chômage des jeunes et des diplômés,rendant cette analyse particulièrement pertinente .
(https://www.data.gov.ma/))
.

In [1]:
import pandas as pd 
df0=pd.read_csv("data1.csv")
df0

,CODE,Milieu de résidence,Durée de chômage,Sexe,1999,2000,2001,2002,2003,2004,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,482,Urbain,Moins de 12 mois,Masculin,26,"26,8","27,7","27,5","26,6","28,1",...,32.4,34.0,37.6,33.8,31.4,29.4,32.2,32.6,44.3,26.1
1,486,Urbain,Moins de 12 mois,Feminin,"20,4","20,9","21,8","21,8","22,1","21,9",...,23.1,32.6,25.5,23.5,22.1,21.0,32.2,22.8,32.5,22.4
2,478,Urbain,Moins de 12 mois,Total,"24,3","25,1",26,"25,8","25,2","26,2",...,29.3,30.9,33.7,30.5,28.2,26.2,32.1,28.9,40.3,24.8
3,483,Urbain,12 à moins de 36 mois,Masculin,"27,7","26,7","25,9","26,1","24,2","26,3",...,25.1,26.1,27.0,28.4,32.2,32.4,32.2,29.2,27.7,42.5
4,487,Urbain,12 à moins de 36 mois,Feminin,"28,8","29,4","27,3","26,6","25,2","28,6",...,31.2,30.9,33.4,34.9,37.8,35.4,32.2,33.8,33.3,43.7
5,479,Urbain,12 à moins de 36 mois,Total,28,"27,5","26,3","26,2","24,5",27,...,27.1,28.1,29.0,30.5,34.1,33.6,32.1,31.0,29.6,43.0
6,484,Urbain,36 à moins de 60 mois,Masculin,"17,5","16,5","17,5","16,5","16,2","15,5",...,15.3,15.0,13.2,14.4,14.9,15.9,32.2,16.4,12.8,14.7
7,488,Urbain,36 à moins de 60 mois,Feminin,"20,2","20,3","19,3",19,"16,8",15,...,16.7,14.7,15.7,16.4,16.5,17.1,32.2,18.9,15.2,14.9
8,480,Urbain,36 à moins de 60 mois,Total,"18,3","17,6",18,"17,2","16,4","15,3",...,15.8,14.7,14.0,15.1,15.4,16.3,32.1,17.4,13.6,14.8
9,485,Urbain,60 mois et plus,Masculin,"28,6","29,9","28,9","29,9",33,"30,2",...,26.7,24.0,21.8,23.0,21.3,22.0,32.2,21.8,15.2,16.7
10,489,Urbain,60 mois et plus,Feminin,"30,6","29,4","31,6","32,6","35,9","34,3",...,28.8,28.1,25.3,25.1,23.3,26.3,32.2,24.5,19.0,18.9
11,481,Urbain,60 mois et plus,Total,"29,2","29,7","29,7","30,7","33,9","31,4",...,27.4,25.1,22.9,23.7,22.0,23.6,32.2,22.8,16.5,17.5
12,494,Rural,Moins de 12 mois,Masculin,"45,3","50,6","53,4","54,1","54,9","57,2",...,57.3,57.1,56.8,52.5,52.1,44.3,32.3,50.3,62.5,44.8
13,462,Rural,Moins de 12 mois,Feminin,"48,3",56,"58,1","57,1","48,6","38,1",...,39.8,50.8,43.8,44.1,37.0,25.8,32.3,32.8,33.4,29.9
14,490,Rural,Moins de 12 mois,Total,"45,7","51,2","53,9","54,5",54,"54,3",...,54.6,56.2,55.0,51.1,49.3,40.4,32.2,47.0,58.1,42.0
15,495,Rural,12 à moins de 36 mois,Masculin,"24,5","22,6","22,9",22,"21,1","19,5",...,21.1,24.3,23.5,26.0,26.0,30.4,32.3,37.3,20.3,34.9
16,463,Rural,12 à moins de 36 mois,Feminin,"20,7",21,"18,2","17,1","17,8","17,3",...,26.0,22.6,31.2,31.5,34.5,35.9,32.3,33.6,35.4,41.0
17,491,Rural,12 à moins de 36 mois,Total,24,"22,4","22,4","21,4","20,6","19,2",...,21.8,24.1,24.5,26.9,27.5,31.6,32.3,28.5,22.6,36.0
18,460,Rural,36 à moins de 60 mois,Masculin,"13,8","12,6","10,9","10,9","10,9","9,3",...,10.4,9.4,8.8,9.1,10.8,12.0,32.3,10.3,8.3,11.5
19,464,Rural,36 à moins de 60 mois,Feminin,"13,2","13,4","13,6","8,3","16,3","17,3",...,12.5,9.5,10.2,9.0,11.3,17.2,32.4,12.8,14.8,12.5
20,492,Rural,36 à moins de 60 mois,Total,"13,7","12,7","11,2","10,6","11,7","10,5",...,10.8,9.4,9.0,9.0,10.9,13.1,32.3,10.7,9.3,11.7
21,461,Rural,60 mois et plus,Masculin,"16,2",14,"12,7","12,9","13,1",14,...,10.9,9.1,10.8,12.3,10.8,13.1,32.3,12.1,8.9,8.7
22,465,Rural,60 mois et plus,Feminin,"17,8","9,5","10,2","17,5","17,2","27,4",...,21.4,17.1,13.6,15.4,16.8,21.1,32.4,20.8,16.4,16.5
23,493,Rural,60 mois et plus,Total,"16,4","13,5","12,4","13,5","13,7",16,...,12.6,10.2,11.2,12.8,11.9,14.8,32.3,13.8,10.0,10.2
24,470,National,Moins de 12 mois,Masculin,"30,5","32,1","33,1","32,7","31,6","33,1",...,38.5,39.3,42.2,38.1,36.4,32.4,32.5,36.2,48.6,29.6
25,474,National,Moins de 12 mois,Feminin,23,"23,5","24,4","24,4",24,"23,2",...,24.9,26.7,27.3,27.9,23.9,21.5,32.9,23.7,32.6,23.1
26,466,National,Moins de 12 mois,Total,"28,4","29,9","30,9","30,5","29,4","30,3",...,34.5,35.8,37.9,13.2,32.6,28.6,32.1,31.8,43.7,27.5
27,471,National,12 à moins de 36 mois,Masculin,27,"25,8","25,3","25,3","23,7","25,1",...,24.1,25.7,26.1,20.6,30.7,32.0,32.6,28.8,25.9,41.1
28,475,National,12 à moins de 36 mois,Feminin,28,"28,7","26,6","25,9","24,7","27,7",...,30.6,31.6,33.2,25.8,37.4,35.5,32.1,33.8,33.5,43.5
29,467,National,12 à moins de 36 mois,Total,"27,3","26,5","25,6","25,4",24,"25,8",...,26.0,27.3,28.1,34.5,32.7,33.2,32.2,31.0,28.2,41.9
30,472,National,36 à moins de 60 mois,Masculin,"16,7","15,7","16,2","15,4","15,3","14,4",...,14.1,13.4,12.2,15.6,13.9,15.1,32.7,15.2,11.7,14.1
31,476,National,36 à moins de 60 mois,Feminin,"19,5","19,8","18,9","18,2","16,8","15,1",...,16.2,14.4,15.1,24.0,15.8,17.1,32.1,18.3,15.2,14.7
32,468,National,36 à moins de 60 mois,Total,"17,5","16,7","16,8","16,2","15,7","14,6",...,14.7,13.7,13.0,34.5,14.5,15.8,32.3,17.4,12.8,14.3
33,473,National,60 mois et plus,Masculin,"25,8","26,4","25,5","26,6","29,5","27,4",...,22.9,21.4,19.2,29.8,18.8,20.2,32.8,19.8,13.7,15.2
34,477,National,60 mois et plus,Feminin,"29,4","27,9",30,"31,5","34,6","33,8",...,28.0,27.1,24.1,13.9,22.5,25.8,32.1,24.2,18.7,18.7
35,469,National,60 mois et plus,Total,"26,7","26,8","26,6","27,9",31,"29,2",...,24.3,23.0,20.6,21.6,19.9,22.2,32.4,21.4,15.2,16.3

In [2]:
df0.shape

(36, 27)

In [3]:
len(df0)

36

In [4]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CODE                 36 non-null     int64
 1   Milieu de résidence  36 non-null     object
 2   Durée de chômage     36 non-null     object
 3   Sexe                 36 non-null     object
 4   1999                 36 non-null     object
 5   2000                 36 non-null     object
 6   2001                 36 non-null     object
 7   2002                 36 non-null     object
 8   2003                 36 non-null     object
 9   2004                 36 non-null     object
 10  2005                 36 non-null     float64
 11  2006                 36 non-null     float64
 12  2007                 36 non-null     float64
 13  2008                 36 non-null     float64
 14  2009                 36 non-null     float64
 15  2010                 36 non-null     float64
 16  2011                 36 non-null     float64
 17  2012                 36 non-null     float64
 18  2013                 36 non-null     float64
 19  2014                 36 non-null     float64
 20  2015                 36 non-null     float64
 21  2016                 36 non-null     float64
 22  2017                 36 non-null     float64
 23  2018                 36 non-null     float64
 24  2019                 36 non-null     float64
 25  2020                 36 non-null     float64
 26  2021                 36 non-null     float64
dtypes: float64(17), int64(1), object(9)
memory usage: 7.7+ KB

In [5]:
df0.describe()

,CODE,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.00000,36.000000,36.000000
mean,477.500000,24.630556,24.991667,24.933333,24.994444,24.952778,24.838889,25.069444,24.913889,25.094444,24.902778,24.958333,24.922222,24.952778,32.294444,25.32500,24.994444,24.991667
std,10.535654,10.272788,11.601709,10.626033,8.932155,9.773243,10.961811,10.043813,10.841195,12.246048,12.255366,11.113554,10.781177,8.492568,0.194120,9.60843,14.109995,12.169948
min,460.000000,9.100000,8.000000,10.700000,10.400000,11.000000,10.200000,12.200000,10.400000,9.100000,8.800000,9.000000,10.800000,12.000000,32.100000,10.30000,8.300000,8.700000
25%,468.750000,16.900000,14.725000,16.700000,18.350000,18.025000,15.600000,16.450000,16.100000,14.700000,13.900000,15.325000,15.700000,17.100000,32.200000,18.07500,14.525000,14.775000
50%,477.500000,24.500000,25.150000,24.500000,25.900000,24.100000,25.100000,24.350000,24.600000,24.700000,24.300000,24.550000,22.900000,24.700000,32.250000,23.95000,19.650000,20.650000
75%,486.250000,30.000000,30.225000,29.100000,29.050000,30.700000,30.250000,29.850000,28.925000,30.900000,31.700000,30.750000,32.625000,32.100000,32.300000,32.00000,33.325000,37.250000
max,495.000000,55.600000,56.300000,54.300000,50.600000,51.700000,54.000000,54.800000,57.300000,57.100000,56.800000,52.500000,52.100000,44.300000,32.900000,50.30000,62.500000,44.800000

In [2]:
df1=pd.read_csv("data3.csv")
df1

,Indicateurs sociaux - Emploi activité et chômage,2002-08,2008,2009,2010,2011,2012,2013
0,"Activité, emploi et chômage (15 ans et plus)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Population active 15 ans et plus (En milliers),"10,849","11,267","11,314","11,415","11,538","11,549","11,705"
2,Urbain,"5,532","5,874","5,916","5,966","5,553","6,655","6,217"
3,Rural,"5,318","5,393","5,398","5,449","5,237","5,404","5,488"
4,Structure de la population active selon les gr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
75,Niveau supérieur,23.5,20.6,19.1,18.5,17.8,17.9,18.1
76,Ayant un diplôme,23.7,19.0,17.8,17.5,19.0,18.6,18.4
77,Taux de chômage rural selon le diplôme (En %),NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Sans diplôme,2.4,2.6,2.5,2.4,2.3,2.4,2.4
79,Ayant un diplôme,11.6,12.2,11.8,11.4,11.1,10.6,9.8

In [3]:
df1.shape

(80, 8)

In [4]:
len(df1)

80

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 8 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Indicateurs sociaux - Emploi activité et chômage  79 non-null     object
 1   2002-08                                           64 non-null     object
 2   2008                                              64 non-null     object
 3   2009                                              64 non-null     object
 4   2010                                              64 non-null     object
 5   2011                                              64 non-null     object
 6   2012                                              64 non-null     object
 7   2013                                              64 non-null     object
dtypes: object(8)
memory usage: 5.1+ KB

In [11]:
df1.describe()

,Indicateurs sociaux - Emploi activité et chômage,2002-08,2008,2009,2010,2011,2012,2013
count,79,64,64,64,64,64,64,64
unique,36,63,61,60,60,63,64,62
top,Urbain,3.6,14.7,11.8,20.2,"5,237","11,549",18.4
freq,8,2,3,2,2,2,1,2

In [12]:
df2=pd.read_csv("data2.csv")
df2

,CODE,Milieu de résidence,Diplôme,1999,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,11164,Urbain,Diplôme et certificat de l’enseignement fondam...,"29,2","29,7","26,1","24,1","25,3","23,9","24,4",...,17.1,17.1,17.8,17.8,16.1,16.4,14.6,13.2,16.0,17.1
1,11165,Urbain,Diplôme de l’enseignement secondaire,"33,1","35,5","34,5","34,4","36,4","32,4","32,5",...,20.2,18.1,19.0,19.5,19.1,21.0,20.4,18.3,19.4,22.0
2,11170,Urbain,Diplôme de l'enseignement supérieur,"31,3","33,2",30,"30,8","30,4","29,3","29,2",...,17.0,17.2,20.0,19.8,20.7,20.9,21.5,19.8,22.4,24.5
3,11171,Urbain,Diplôme de technicien et de cadre moyen,"19,7","20,7","19,2","18,5","19,3","21,9","21,2",...,19.5,19.9,22.2,22.7,24.4,26.1,24.4,23.9,26.3,29.0
4,11175,Urbain,Diplôme en qualification professionnelle,"34,3","31,5","29,9","28,5","27,9","28,3","27,3",...,21.1,22.1,23.0,28.6,23.2,22.7,21.9,20.2,23.5,NaN
5,11177,Urbain,Certificats en spécialisation professionnelle,39,"40,1","35,7","36,6",39,"33,3","37,2",...,22.3,26.6,30.4,26.6,27.0,27.3,23.7,20.4,28.8,NaN
6,11179,Urbain,Sans diplôme,"15,2","13,1","11,8","10,4","11,3","10,6","10,2",...,6.9,8.1,8.0,7.3,6.3,6.7,5.7,5.2,8.5,7.8
7,11184,Urbain,Total,22,"21,4","19,5","18,3","19,3","18,4","18,4",...,13.4,14.0,14.8,14.6,14.2,14.7,13.8,12.9,15.8,NaN
8,11166,Rural,Diplôme et certificat de l’enseignement fondam...,"14,9","13,9","12,6","10,2","8,7","8,8","7,9",...,8.8,8.3,8.0,8.3,7.8,8.0,6.7,6.4,9.7,8.3
9,11167,Rural,Diplôme de l’enseignement secondaire,27,"29,1","29,6","29,7","30,4",20,"17,5",...,13.4,16.1,15.6,15.9,25.8,22.9,22.8,20.5,18.1,21.2
10,11172,Rural,Diplôme de l'enseignement supérieur,"58,5",65,"60,6","53,1","52,6","38,9","43,3",...,32.9,41.0,41.0,33.6,43.0,34.8,38.3,34.4,40.0,35.1
11,11173,Rural,Diplôme de technicien et de cadre moyen,"15,2","13,1","10,4","8,6","10,9","12,2","15,1",...,17.6,16.1,20.4,22.4,20.6,22.2,20.9,25.1,28.8,24.3
12,11178,Rural,Diplôme en qualification professionnelle,"30,1","23,1","18,6","26,9","19,6","18,1","16,6",...,20.9,15.4,12.6,19.3,18.3,19.2,16.7,14.3,19.2,NaN
13,11180,Rural,Certificats en spécialisation professionnelle,"43,9","23,1","37,6","26,1","21,8","21,9","23,7",...,20.5,3.7,17.3,16.5,12.6,16.0,15.3,24.3,26.8,NaN
14,11182,Rural,Sans diplôme,"3,8","3,5",3,"2,5","2,2",2,"2,5",...,2.3,2.4,2.7,2.3,2.1,1.9,1.7,1.7,3.3,2.1
15,11186,Rural,Total,"5,4",5,"4,5","3,8","3,4","3,1","3,6",...,4.0,3.8,4.2,4.1,4.0,4.0,3.6,3.7,5.9,NaN
16,11168,National,Diplôme et certificat de l’enseignement fondam...,"25,4","25,6","22,7","20,5","20,8","19,6","19,7",...,14.3,14.0,14.3,14.4,13.5,13.7,12.1,11.0,14.1,14.3
17,11169,National,Diplôme de l’enseignement secondaire,"32,5",35,"34,1",34,"35,8","31,1","30,8",...,19.2,18.2,17.3,19.1,19.7,21.2,20.6,18.6,19.2,21.8
18,11174,National,Diplôme de l'enseignement supérieur,"32,9","35,2",32,"32,3","31,6","29,9","30,3",...,17.8,18.3,21.3,20.8,22.2,22.1,22.5,20.9,23.9,25.4
19,11176,National,Diplôme de technicien et de cadre moyen,"19,8","20,3","18,8",18,"18,8","21,6","21,1",...,19.4,19.7,22.1,22.7,24.2,25.9,24.2,23.9,26.4,28.8
20,11181,National,Diplôme en qualification professionnelle,34,"30,8",29,"28,4","27,3","27,5","26,5",...,21.0,21.4,21.8,22.4,22.7,22.3,21.3,19.4,23.0,NaN
21,11183,National,Certificats en spécialisation professionnelle,"39,7","37,9","35,9","35,5","37,4","32,1","35,8",...,22.0,22.1,28.1,24.2,24.3,25.7,22.5,20.9,28.4,NaN
22,11185,National,Sans diplôme,8,7,"6,3","5,5","5,5",5,"5,2",...,4.0,4.5,4.7,4.7,3.9,3.8,3.3,3.1,5.6,4.6
23,11163,National,Total,"13,8","13,4","12,3","11,3","11,5","10,8","11,1",...,9.0,9.2,9.9,9.7,9.9,10.2,9.5,9.2,11.9,NaN

#### On elimine les colonnes dont les valeurs sont NULL

In [ ]:
for i in range(1996,1999):
    df0.drop(str(i),axis=1, inplace=True)

In [14]:
df0

,CODE,Milieu de résidence,Durée de chômage,Sexe,1999,2000,2001,2002,2003,2004,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,482,Urbain,Moins de 12 mois,Masculin,26,"26,8","27,7","27,5","26,6","28,1",...,32.4,34.0,37.6,33.8,31.4,29.4,32.2,32.6,44.3,26.1
1,486,Urbain,Moins de 12 mois,Feminin,"20,4","20,9","21,8","21,8","22,1","21,9",...,23.1,32.6,25.5,23.5,22.1,21.0,32.2,22.8,32.5,22.4
2,478,Urbain,Moins de 12 mois,Total,"24,3","25,1",26,"25,8","25,2","26,2",...,29.3,30.9,33.7,30.5,28.2,26.2,32.1,28.9,40.3,24.8
3,483,Urbain,12 à moins de 36 mois,Masculin,"27,7","26,7","25,9","26,1","24,2","26,3",...,25.1,26.1,27.0,28.4,32.2,32.4,32.2,29.2,27.7,42.5
4,487,Urbain,12 à moins de 36 mois,Feminin,"28,8","29,4","27,3","26,6","25,2","28,6",...,31.2,30.9,33.4,34.9,37.8,35.4,32.2,33.8,33.3,43.7
5,479,Urbain,12 à moins de 36 mois,Total,28,"27,5","26,3","26,2","24,5",27,...,27.1,28.1,29.0,30.5,34.1,33.6,32.1,31.0,29.6,43.0
6,484,Urbain,36 à moins de 60 mois,Masculin,"17,5","16,5","17,5","16,5","16,2","15,5",...,15.3,15.0,13.2,14.4,14.9,15.9,32.2,16.4,12.8,14.7
7,488,Urbain,36 à moins de 60 mois,Feminin,"20,2","20,3","19,3",19,"16,8",15,...,16.7,14.7,15.7,16.4,16.5,17.1,32.2,18.9,15.2,14.9
8,480,Urbain,36 à moins de 60 mois,Total,"18,3","17,6",18,"17,2","16,4","15,3",...,15.8,14.7,14.0,15.1,15.4,16.3,32.1,17.4,13.6,14.8
9,485,Urbain,60 mois et plus,Masculin,"28,6","29,9","28,9","29,9",33,"30,2",...,26.7,24.0,21.8,23.0,21.3,22.0,32.2,21.8,15.2,16.7
10,489,Urbain,60 mois et plus,Feminin,"30,6","29,4","31,6","32,6","35,9","34,3",...,28.8,28.1,25.3,25.1,23.3,26.3,32.2,24.5,19.0,18.9
11,481,Urbain,60 mois et plus,Total,"29,2","29,7","29,7","30,7","33,9","31,4",...,27.4,25.1,22.9,23.7,22.0,23.6,32.2,22.8,16.5,17.5
12,494,Rural,Moins de 12 mois,Masculin,"45,3","50,6","53,4","54,1","54,9","57,2",...,57.3,57.1,56.8,52.5,52.1,44.3,32.3,50.3,62.5,44.8
13,462,Rural,Moins de 12 mois,Feminin,"48,3",56,"58,1","57,1","48,6","38,1",...,39.8,50.8,43.8,44.1,37.0,25.8,32.3,32.8,33.4,29.9
14,490,Rural,Moins de 12 mois,Total,"45,7","51,2","53,9","54,5",54,"54,3",...,54.6,56.2,55.0,51.1,49.3,40.4,32.2,47.0,58.1,42.0
15,495,Rural,12 à moins de 36 mois,Masculin,"24,5","22,6","22,9",22,"21,1","19,5",...,21.1,24.3,23.5,26.0,26.0,30.4,32.3,37.3,20.3,34.9
16,463,Rural,12 à moins de 36 mois,Feminin,"20,7",21,"18,2","17,1","17,8","17,3",...,26.0,22.6,31.2,31.5,34.5,35.9,32.3,33.6,35.4,41.0
17,491,Rural,12 à moins de 36 mois,Total,24,"22,4","22,4","21,4","20,6","19,2",...,21.8,24.1,24.5,26.9,27.5,31.6,32.3,28.5,22.6,36.0
18,460,Rural,36 à moins de 60 mois,Masculin,"13,8","12,6","10,9","10,9","10,9","9,3",...,10.4,9.4,8.8,9.1,10.8,12.0,32.3,10.3,8.3,11.5
19,464,Rural,36 à moins de 60 mois,Feminin,"13,2","13,4","13,6","8,3","16,3","17,3",...,12.5,9.5,10.2,9.0,11.3,17.2,32.4,12.8,14.8,12.5
20,492,Rural,36 à moins de 60 mois,Total,"13,7","12,7","11,2","10,6","11,7","10,5",...,10.8,9.4,9.0,9.0,10.9,13.1,32.3,10.7,9.3,11.7
21,461,Rural,60 mois et plus,Masculin,"16,2",14,"12,7","12,9","13,1",14,...,10.9,9.1,10.8,12.3,10.8,13.1,32.3,12.1,8.9,8.7
22,465,Rural,60 mois et plus,Feminin,"17,8","9,5","10,2","17,5","17,2","27,4",...,21.4,17.1,13.6,15.4,16.8,21.1,32.4,20.8,16.4,16.5
23,493,Rural,60 mois et plus,Total,"16,4","13,5","12,4","13,5","13,7",16,...,12.6,10.2,11.2,12.8,11.9,14.8,32.3,13.8,10.0,10.2
24,470,National,Moins de 12 mois,Masculin,"30,5","32,1","33,1","32,7","31,6","33,1",...,38.5,39.3,42.2,38.1,36.4,32.4,32.5,36.2,48.6,29.6
25,474,National,Moins de 12 mois,Feminin,23,"23,5","24,4","24,4",24,"23,2",...,24.9,26.7,27.3,27.9,23.9,21.5,32.9,23.7,32.6,23.1
26,466,National,Moins de 12 mois,Total,"28,4","29,9","30,9","30,5","29,4","30,3",...,34.5,35.8,37.9,13.2,32.6,28.6,32.1,31.8,43.7,27.5
27,471,National,12 à moins de 36 mois,Masculin,27,"25,8","25,3","25,3","23,7","25,1",...,24.1,25.7,26.1,20.6,30.7,32.0,32.6,28.8,25.9,41.1
28,475,National,12 à moins de 36 mois,Feminin,28,"28,7","26,6","25,9","24,7","27,7",...,30.6,31.6,33.2,25.8,37.4,35.5,32.1,33.8,33.5,43.5
29,467,National,12 à moins de 36 mois,Total,"27,3","26,5","25,6","25,4",24,"25,8",...,26.0,27.3,28.1,34.5,32.7,33.2,32.2,31.0,28.2,41.9
30,472,National,36 à moins de 60 mois,Masculin,"16,7","15,7","16,2","15,4","15,3","14,4",...,14.1,13.4,12.2,15.6,13.9,15.1,32.7,15.2,11.7,14.1
31,476,National,36 à moins de 60 mois,Feminin,"19,5","19,8","18,9","18,2","16,8","15,1",...,16.2,14.4,15.1,24.0,15.8,17.1,32.1,18.3,15.2,14.7
32,468,National,36 à moins de 60 mois,Total,"17,5","16,7","16,8","16,2","15,7","14,6",...,14.7,13.7,13.0,34.5,14.5,15.8,32.3,17.4,12.8,14.3
33,473,National,60 mois et plus,Masculin,"25,8","26,4","25,5","26,6","29,5","27,4",...,22.9,21.4,19.2,29.8,18.8,20.2,32.8,19.8,13.7,15.2
34,477,National,60 mois et plus,Feminin,"29,4","27,9",30,"31,5","34,6","33,8",...,28.0,27.1,24.1,13.9,22.5,25.8,32.1,24.2,18.7,18.7
35,469,National,60 mois et plus,Total,"26,7","26,8","26,6","27,9",31,"29,2",...,24.3,23.0,20.6,21.6,19.9,22.2,32.4,21.4,15.2,16.3

In [ ]:
df2.drop('1977', axis=1, inplace=True)

In [ ]:
for i in range(1978,1999):
    df2.drop(str(i),axis=1, inplace=True)

In [15]:
df2

,CODE,Milieu de résidence,Diplôme,1999,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,11164,Urbain,Diplôme et certificat de l’enseignement fondam...,"29,2","29,7","26,1","24,1","25,3","23,9","24,4",...,17.1,17.1,17.8,17.8,16.1,16.4,14.6,13.2,16.0,17.1
1,11165,Urbain,Diplôme de l’enseignement secondaire,"33,1","35,5","34,5","34,4","36,4","32,4","32,5",...,20.2,18.1,19.0,19.5,19.1,21.0,20.4,18.3,19.4,22.0
2,11170,Urbain,Diplôme de l'enseignement supérieur,"31,3","33,2",30,"30,8","30,4","29,3","29,2",...,17.0,17.2,20.0,19.8,20.7,20.9,21.5,19.8,22.4,24.5
3,11171,Urbain,Diplôme de technicien et de cadre moyen,"19,7","20,7","19,2","18,5","19,3","21,9","21,2",...,19.5,19.9,22.2,22.7,24.4,26.1,24.4,23.9,26.3,29.0
4,11175,Urbain,Diplôme en qualification professionnelle,"34,3","31,5","29,9","28,5","27,9","28,3","27,3",...,21.1,22.1,23.0,28.6,23.2,22.7,21.9,20.2,23.5,NaN
5,11177,Urbain,Certificats en spécialisation professionnelle,39,"40,1","35,7","36,6",39,"33,3","37,2",...,22.3,26.6,30.4,26.6,27.0,27.3,23.7,20.4,28.8,NaN
6,11179,Urbain,Sans diplôme,"15,2","13,1","11,8","10,4","11,3","10,6","10,2",...,6.9,8.1,8.0,7.3,6.3,6.7,5.7,5.2,8.5,7.8
7,11184,Urbain,Total,22,"21,4","19,5","18,3","19,3","18,4","18,4",...,13.4,14.0,14.8,14.6,14.2,14.7,13.8,12.9,15.8,NaN
8,11166,Rural,Diplôme et certificat de l’enseignement fondam...,"14,9","13,9","12,6","10,2","8,7","8,8","7,9",...,8.8,8.3,8.0,8.3,7.8,8.0,6.7,6.4,9.7,8.3
9,11167,Rural,Diplôme de l’enseignement secondaire,27,"29,1","29,6","29,7","30,4",20,"17,5",...,13.4,16.1,15.6,15.9,25.8,22.9,22.8,20.5,18.1,21.2
10,11172,Rural,Diplôme de l'enseignement supérieur,"58,5",65,"60,6","53,1","52,6","38,9","43,3",...,32.9,41.0,41.0,33.6,43.0,34.8,38.3,34.4,40.0,35.1
11,11173,Rural,Diplôme de technicien et de cadre moyen,"15,2","13,1","10,4","8,6","10,9","12,2","15,1",...,17.6,16.1,20.4,22.4,20.6,22.2,20.9,25.1,28.8,24.3
12,11178,Rural,Diplôme en qualification professionnelle,"30,1","23,1","18,6","26,9","19,6","18,1","16,6",...,20.9,15.4,12.6,19.3,18.3,19.2,16.7,14.3,19.2,NaN
13,11180,Rural,Certificats en spécialisation professionnelle,"43,9","23,1","37,6","26,1","21,8","21,9","23,7",...,20.5,3.7,17.3,16.5,12.6,16.0,15.3,24.3,26.8,NaN
14,11182,Rural,Sans diplôme,"3,8","3,5",3,"2,5","2,2",2,"2,5",...,2.3,2.4,2.7,2.3,2.1,1.9,1.7,1.7,3.3,2.1
15,11186,Rural,Total,"5,4",5,"4,5","3,8","3,4","3,1","3,6",...,4.0,3.8,4.2,4.1,4.0,4.0,3.6,3.7,5.9,NaN
16,11168,National,Diplôme et certificat de l’enseignement fondam...,"25,4","25,6","22,7","20,5","20,8","19,6","19,7",...,14.3,14.0,14.3,14.4,13.5,13.7,12.1,11.0,14.1,14.3
17,11169,National,Diplôme de l’enseignement secondaire,"32,5",35,"34,1",34,"35,8","31,1","30,8",...,19.2,18.2,17.3,19.1,19.7,21.2,20.6,18.6,19.2,21.8
18,11174,National,Diplôme de l'enseignement supérieur,"32,9","35,2",32,"32,3","31,6","29,9","30,3",...,17.8,18.3,21.3,20.8,22.2,22.1,22.5,20.9,23.9,25.4
19,11176,National,Diplôme de technicien et de cadre moyen,"19,8","20,3","18,8",18,"18,8","21,6","21,1",...,19.4,19.7,22.1,22.7,24.2,25.9,24.2,23.9,26.4,28.8
20,11181,National,Diplôme en qualification professionnelle,34,"30,8",29,"28,4","27,3","27,5","26,5",...,21.0,21.4,21.8,22.4,22.7,22.3,21.3,19.4,23.0,NaN
21,11183,National,Certificats en spécialisation professionnelle,"39,7","37,9","35,9","35,5","37,4","32,1","35,8",...,22.0,22.1,28.1,24.2,24.3,25.7,22.5,20.9,28.4,NaN
22,11185,National,Sans diplôme,8,7,"6,3","5,5","5,5",5,"5,2",...,4.0,4.5,4.7,4.7,3.9,3.8,3.3,3.1,5.6,4.6
23,11163,National,Total,"13,8","13,4","12,3","11,3","11,5","10,8","11,1",...,9.0,9.2,9.9,9.7,9.9,10.2,9.5,9.2,11.9,NaN

In [16]:
df2.shape

(24, 26)

In [17]:
df2.describe()

,CODE,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.00000,24.000000,24.000000,24.000000,24.000000,24.000000,15.000000
mean,11174.500000,17.270833,17.241667,16.025000,15.720833,17.354167,17.38750,17.733333,17.904167,17.000000,16.304167,19.375000,19.086667
std,7.071068,8.485460,8.746672,7.199049,8.543545,8.839633,8.03126,9.303700,8.508997,8.688223,8.285004,8.963416,9.764064
min,11163.000000,2.400000,2.300000,2.300000,2.400000,2.700000,2.30000,2.100000,1.900000,1.700000,1.700000,3.300000,2.100000
25%,11168.750000,12.625000,12.375000,12.300000,8.975000,11.925000,13.22500,11.925000,12.825000,11.450000,10.550000,13.550000,11.300000
50%,11174.500000,17.350000,18.000000,17.700000,16.600000,17.550000,19.20000,19.400000,20.950000,20.500000,19.000000,19.300000,21.800000
75%,11180.250000,20.650000,20.175000,20.600000,19.750000,21.875000,22.47500,23.450000,22.750000,22.500000,20.900000,26.325000,24.950000
max,11186.000000,34.000000,35.100000,32.900000,41.000000,41.000000,33.60000,43.000000,34.800000,38.300000,34.400000,40.000000,35.100000

In [18]:
len(df2)

24

In [ ]:
df0.to_csv('data1.csv',index=False)

In [ ]:
df1.to_csv('data3.csv',index=False)

In [ ]:
df2.to_csv('data2.csv',index=False)

on filtre pour choisir les deux sexe et le niveau national

In [6]:
import pandas as pd
df=pd.read_csv('data1.csv')
dff=df[df['Milieu de résidence']=='National'] 
dff=dff[dff['Sexe']=='Total'] 
dff

,CODE,Milieu de résidence,Durée de chômage,Sexe,1999,2000,2001,2002,2003,2004,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
26,466,National,Moins de 12 mois,Total,"28,4","29,9","30,9","30,5","29,4","30,3",...,34.5,35.8,37.9,13.2,32.6,28.6,32.1,31.8,43.7,27.5
29,467,National,12 à moins de 36 mois,Total,"27,3","26,5","25,6","25,4",24,"25,8",...,26.0,27.3,28.1,34.5,32.7,33.2,32.2,31.0,28.2,41.9
32,468,National,36 à moins de 60 mois,Total,"17,5","16,7","16,8","16,2","15,7","14,6",...,14.7,13.7,13.0,34.5,14.5,15.8,32.3,17.4,12.8,14.3
35,469,National,60 mois et plus,Total,"26,7","26,8","26,6","27,9",31,"29,2",...,24.3,23.0,20.6,21.6,19.9,22.2,32.4,21.4,15.2,16.3